name: ImmortalWrt Builder

on:
  workflow_dispatch:
    inputs:
      immver:
        description: 'ImmortalWrt version'
        required: true
        default: '21.02.7'
        type: choice
        options:
          - 21.02.7
          - 24.10.4

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jembyte/immobuild:latest
      options: --user runner

    steps:
      #- name: Fix permissions
      #  run: |
      #    fdir="$(echo $PWD | awk -F '/' '{print "/"$2}')"
      #    ls -ld $fdir
      #    sudo chown -R ubuntu:ubuntu $fdir

      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone source code
        run: |
          git clone \
          -b v${{ inputs.immver }} \
          --single-branch \
          --filter=blob:none \
          --depth=1 \
          https://github.com/immortalwrt/immortalwrt.git

      - name: Update and install feeds
        run: |
          cd immortalwrt
          scripts/feeds update -a
          scripts/feeds install -a

      - name: Prepare build
        run: |
          cat config_${{ inputs.immver }}.buildinfo > immortalwrt/.config
          cd immortalwrt
          patch -p1 < ../tl-wr840n-v6.20_${{ inputs.immver }}.patch

          make defconfig

      - name: Build ImmortalWrt
        #env:
        #  FORCE_UNSAFE_CONFIGURE: 1
        run: |
          cd immortalwrt
          make -j$(nproc --all)

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: tl-wr840n-v6.20_immo-${{ inputs.immver }}
          path: immortalwrt/bin/targets/ramips/mt76x8
